replicaCount: 2

nameOverride: app

image:
  repository: mobikop/crud-app

app:
  port: 8080

service:
  type: NodePort
  port: 80

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"
  persistence:
    size: 1Gi